### ISSUE TITLE
NPE with bad application identifier

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ets-gpkg10#13]
```
bradh@marginata:~/ets-gpkg10$ java -jar target/ets-gpkg10-0.3-SNAPSHOT-aio.jar 
[Fatal Error] testng-results.xml:103:145: An invalid XML character (Unicode: 0x0) was found in the CDATA section.
Aug 30, 2016 7:40:54 PM com.occamlab.te.spi.executors.testng.TestNGExecutor execute
SEVERE: Failed to parse test results.
org.xml.sax.SAXParseException; systemId: file:/home/bradh/testng/286de377-b5e5-4729-8ae2-84677017bb12/testng-results.xml; lineNumber: 103; columnNumber: 145; An invalid XML character (Unicode: 0x0) was found in the CDATA section.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
        at com.occamlab.te.spi.executors.testng.TestNGExecutor.parseResultsDoc(TestNGExecutor.java:133)
        at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:118)
        at org.opengis.cite.gpkg10.TestNGController.doTestRun(TestNGController.java:122)
        at org.opengis.cite.gpkg10.TestNGController.main(TestNGController.java:70)

Exception in thread "main" java.lang.NullPointerException
        at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:122)
        at org.opengis.cite.gpkg10.TestNGController.doTestRun(TestNGController.java:122)
        at org.opengis.cite.gpkg10.TestNGController.main(TestNGController.java:70)
```

Looks like that needs to be escaped or converted to hex...

**Comment by moran0013** [comment]
can you post the xml in question, or possibly the data used to create this?

**Comment by moran0013** [comment]
actually, found out how to repeat. updated code to simply print out the array of values rather than an encoded string.
